openapi: 3.0.3
info:
  title: Camara common data types
  description: Common data types for Camara APIs
  contact:
    email: sp-com@lists.camaraproject.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.4.0
paths: {}
