type: string
example: 192.168.0.1/24
description: |
  IPv4 address may be specified in form <address/mask> as:
    - address - an IPv4 number in dotted-quad form 1.2.3.4. Only this exact IP number will match the flow control rule.
    - address/mask - an IP number as above with a mask width of the form 1.2.3.4/24.
      In this case, all IP numbers from 1.2.3.0 to 1.2.3.255 will match. The bit width MUST be valid for the IP version.
