# This is a basic workflow to help you get started with Actions

name: Redocly bundle QoD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bundle"
  bundle:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Test Redoc
    steps:
      # first checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # then use redocly-cli-github-action
      - name: Redocly CLI Test
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'bundle qod/openapi.yaml --output qod/bundled.yaml'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bundled OAS
          path: qod/bundled.yaml
          
      - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Bundled OAS
